#include <stdio.h>
#include <stdlib.h>

int main(void) {
    const char *model =
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "`.\n"
        " |\n"
        " |\n"
        " |\n"
        " |\n"
        " |\n"
        " |\n"
        " |   __\n"
        " |-``\n"
        " |\n"
        " |\n"
        " |--'''\n"
        " |\n"
        " |\n"
        " |\n"
        " |--          ........\n"
        " |\n"
        " |\n"
        " |\n"
        " |--'''\n"
        " |\n"
        " |\n"
        " |-..__\n"
        " |\n"
        " |\n"
        " |\n"
        " |\n"
        " |\n"
        " |\n"
        ".'\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n"
        "|\n";

    printf("%s\n", model);
    return EXIT_SUCCESS;
}
